### ISSUE TITLE
Discuss DocBook to CommonMark transition

### ISSUE THREAD

**Issue by ryantm** [nix-community/nixdoc#23]
Hi!

It recently came to my attention that this project is [used in the nixpkgs manual](https://github.com/NixOS/nixpkgs/blob/master/doc/doc-support/lib-function-docs.nix). We've recently accepted a community proposal to change the manual from [DocBook to CommonMark](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md) and are [working on transitioning.](https://github.com/NixOS/nixpkgs/projects/37). We are changing one section from DocBook to CommonMark at a time. Until we're done, we are using Pandoc to convert them back to DocBook for inclusion into the manual.

I am opening this issue to discuss if it makes sense to convert this library to output CommonMark instead of Docbook. Or, maybe it makes sense to use some other tool. Any advice would be appreciated.

\- Ryan

**Comment by roberth** [comment]
Nixpkgs' choice for markdown makes the choice for markup in comments (#5) a no-brainer.

**Comment by tazjin** [comment]
> if it makes sense to convert this library to output CommonMark instead of Docbook

That's probably reasonable! Depending on the structure you're opting for it's likely much easier than the current docbook generation step.

I've moved this repository over to the `nix-community` organisation, and it's maintained by the `docs` team there - feel free to join if you're interested, especially because I don't know how much time I have for this at the moment (likely not much).

**Comment by asymmetric** [comment]
This has been closed by #25.

**Comment by mightyiam** [comment]
Thank you.
